stages:
  - test
  - deploy

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

cache:
  paths:
    - node_modules/

.prepare:
  image: node:latest
  before_script:
    - node --version
    - npm --version
    - npm install

test:
  stage: test
  extends: .prepare
  script:
    - npm run fix-style
    - npm run check-style
    - node_modules/.bin/nyc node_modules/.bin/ava test/*.js

deploy:
  stage: deploy
  extends: .prepare
  script:
    - node_modules/.bin/cyclonedx-bom
    - curl -X "POST" "$BOM_SERVER" -H "Content-Type:multipart/form-data" -H "X-Api-Key:$BOM_KEY" -F "project=$BOM_PROJECT" -F "bom=@bom.xml"
