image: node:latest

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

cache:
  paths:
    - node_modules/

test:
  script:
    - npm install
    - npm run fix-style
    - npm run check-style
    - node_modules/.bin/nyc node_modules/.bin/ava test/*.js

