filter:
    paths:
        - lib/
        - test/
    dependency_paths:
        - node_modules/
checks:
    javascript: true
build:
    nodes:
        analysis:
            tests:
                override:
                    - node_modules/.bin/standard --fix "lib/*.mjs" "test/*.js"
                    - node_modules/.bin/standard "lib/*.mjs" "test/*.js"
                    -
                        command: node_modules/.bin/nyc --extension .mjs --reporter=clover node_modules/.bin/ava test/*.js
                        coverage:
                            file: coverage/clover.xml
                            format: clover
                    - js-scrutinizer-run
