filter:
    paths:
        - bin/
        - lib/
        - test/
    dependency_paths:
        - node_modules/
checks:
    javascript: true
build:
    nodes:
        analysis:
            tests:
                override:
                    - node_modules/.bin/standard --fix "bin/**/*.js" "lib/**/*.js" "test/**/*.js"
                    - node_modules/.bin/standard "bin/**/*.js" "lib/**/*.js" "test/**/*.js"
                    -
                        command: node_modules/.bin/nyc --reporter=clover node_modules/.bin/mocha test/*Test.js
                        coverage:
                            file: coverage/clover.xml
                            format: clover
                    - js-scrutinizer-run
